name: McDavid Drawing
favicon: null
layout_spectrum: 0.96687
typography_spectrum: 0.1309986
title: mcdavid drawing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9c9b6'
    - '#c7b89f'
    - '#7d7081'
    - '#9f9289'
    - '#54465d'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
